name: Add issues to project

on:
  issues:
    types:
      - opened

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@d79571d8737ce0caa0120f44b15f2bc8f193d11a
        with:
          project-url: https://github.com/users/iolave/projects/3
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
          labeled: feature, test, refactor, chore
          label-operator: OR
